CREATE DATABASE TEST;
USE TEST;
CREATE TABLE PERSONS(
  PERSON_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  FIRST_NAME VARCHAR(25),
  MIDDLE_NAME VARCHAR(25),
  LAST_NAME VARCHAR(25),
  SEX CHAR(1),
  DATE_OF_BIRTH DATE,
  DATE_MEMBERSHIP_BEGAN DATE NULL,
  DATE_MEMBERSHIP_ENDED DATE NULL,
  DATE_VISITED_CHURCH DATE NULL,
  ACTIVE CHAR(1) NOT NULL
)
AUTO_INCREMENT=50, ENGINE=InnoDB;

CREATE TABLE ADDRESSES(
  ADDRESS_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  STREET_1 VARCHAR(50),
  STREET_2 VARCHAR(50),
  CITY VARCHAR(50),
  STATE VARCHAR(2),
  ZIP VARCHAR(10),
  ACTIVE CHAR(1) NOT NULL,
  PERSON_ID INT NOT NULL,
  FOREIGN KEY(PERSON_ID) REFERENCES PERSONS(PERSON_ID)
)
AUTO_INCREMENT=50, ENGINE=InnoDB;

CREATE TABLE CONTACTS(
  CONTACT_ID INT NOT NULL AUTO_INCREMENT,
  PERSON_ID INT NOT NULL,
  CONTACT_DATETIME DATETIME,
  ACTIVE CHAR(1) NOT NULL,
  PRIMARY KEY(CONTACT_ID),
  FOREIGN KEY(PERSON_ID) REFERENCES PERSONS(PERSON_ID)
)
AUTO_INCREMENT=50, ENGINE=InnoDB;

CREATE TABLE PHONE_NUMBERS(
  PHONE_NUMBER_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  PERSON_ID INT NOT NULL,
  AREA_CODE INT(3),
  PHONE_NUMBER VARCHAR(8),
  ACTIVE CHAR(1) NOT NULL,
  FOREIGN KEY(PERSON_ID) REFERENCES PERSONS(PERSON_ID)
)
AUTO_INCREMENT=50, ENGINE=InnoDB;

