INSERT INTO PERSONS(FIRST_NAME,MIDDLE_NAME,LAST_NAME,SEX,DATE_OF_BIRTH,DATE_MEMBERSHIP_BEGAN,DATE_MEMBERSHIP_ENDED,ACTIVE)
VALUES('Brian','J','Beech','M',NULL,NOW(),NULL,1),
('Timothy','','Mercer','M',NULL,NOW(),NULL,1),
('Kimberly','Diane','Beech','F',NULL,NOW(),NULL,1);

INSERT INTO ADDRESSES(PERSON_ID,STREET_1,CITY,STATE,ZIP,ACTIVE)
VALUES(50,'2205 Grandview Dr.','Floyds Knobs','IN','47119',1),
(51,'303 School St.','Stonewall','MS',null,1),
(52,'3 Beth Cove','Long Beach','MS','39560',1)